### PR TITLE
correct git url structure for csstree dependency

### PR DESCRIPTION
**Pull request by balupton**
Fixes: npm ERR! exited with error code: 128
https://github.com/npm/npm/issues/16830

```
2631 silly fetchPackageMetaData error for csstree@git+https://github.com/cgiffard/CSSTree.git#inline-comments exited with error code: 128
2632 silly pacote range manifest for cheerio@^0.19.0 fetched in 26ms
2633 silly resolveWithNewModule cheerio@0.19.0 checking installable status
2634 silly pacote range manifest for iconv-lite@^0.4.13 fetched in 22ms
2635 silly resolveWithNewModule iconv-lite@0.4.18 checking installable status
2636 silly pacote range manifest for simplecrawler@^0.5.4 fetched in 23ms
2637 silly resolveWithNewModule simplecrawler@0.5.4 checking installable status
2638 silly pacote range manifest for text-statistics@^0.1.1 fetched in 24ms
2639 silly resolveWithNewModule text-statistics@0.1.1 checking installable status
2640 silly pacote version manifest for yoyaku@0.0.12 fetched in 24ms
2641 silly resolveWithNewModule yoyaku@0.0.12 checking installable status
2642 verbose stack Error: exited with error code: 128
2642 verbose stack     at ChildProcess.onexit (/opt/node-v4.4.6-linux-x64/lib/node_modules/npm/node_modules/mississippi/node_modules/end-of-stream/index.js:39:36)
2642 verbose stack     at emitTwo (events.js:87:13)
2642 verbose stack     at ChildProcess.emit (events.js:172:7)
2642 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
2643 verbose cwd /home/ec2-user/app/current
2644 verbose Linux 4.4.51-40.58.amzn1.x86_64
2645 verbose argv "/opt/node-v4.4.6-linux-x64/bin/node" "/usr/local/nodejs/bin/npm" "install"
2646 verbose node v4.4.6
2647 verbose npm  v5.0.3
2648 error exited with error code: 128
2649 verbose exit [ 1, true ]
```

### CODE REVIEW

**Review by cgiffard — APPROVED** [review]
Thanks ben, looks good. Sorry for that!

**Comment by balupton** [comment]
ha! travis really didn't like that move from https to ssh - https://travis-ci.org/cgiffard/Behaviour-Assertion-Sheets/builds/244772822?utm_source=github_status&utm_medium=notification

let me find out the https equivalent

**Comment by cgiffard** [comment]
@balupton This is failing CI though — do we need to work out another method for travis? Do you think it needs a key?

**Comment by balupton** [comment]
trying a new way, one moment

**Comment by balupton** [comment]
@cgiffard winning! good for merge, github also has a squash option on the github merge button dropdown if you want to squash those commits - up to you mate!

**Comment by cgiffard** [comment]
@balupton Great, thanks! Pushing an update to npm now.

**Comment by cgiffard** [comment]
Published.

**Comment by balupton** [comment]
great thanks!

**Pull request merged**
